# Generated by Django 4.1 on 2022-09-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=100)),
                ('class_id', models.CharField(db_column='class_id', max_length=50, unique=True)),
                ('credits_number', models.FloatField(db_column='credits_number')),
                ('teacher_name', models.CharField(db_column='teacher_name', max_length=100)),
                ('schedule', models.CharField(db_column='schedule_', max_length=100)),
                ('week', models.CharField(db_column='week_', max_length=50)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('registered', models.IntegerField(db_column='registered')),
                ('is_clc', models.BooleanField(db_column='is_clc')),
            ],
            options={
                'db_table': 'term',
            },
        ),
    ]
